mymeal/recipes/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, IntegerField, SelectField
from wtforms.validators import DataRequired


class RecipeForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    serves_choices = [('1','1'), ('2', '2'),('3', '3'),('4', '4'),('5', '5'),('6', '6'),('7', '7'),('8', '8'),('9', '9')]
    serves = SelectField('Serves How Many', choices=serves_choices, validators=[DataRequired()])
    description = TextAreaField('Description', validators=[DataRequired()])
    recipe_type_choices = [('snack', 'Snack'), ('lunch', 'Lunch'),('dinner', 'Dinner'),('dessert', 'Dessert')]
    recipe_type = SelectField('Recipe Type', choices=recipe_type_choices, validators=[DataRequired()])
    recipe_book = StringField('Recipe Book')
    recipe_book_page = IntegerField('Page Number')
    submit = SubmitField('Create')

mymeal/ingredients/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from mymeal.models import Ingredient, Recipe
from mymeal.ingredients.forms import IngredientForm
from flask_login import login_required
from mymeal import db


ingredients = Blueprint('ingredients', __name__)


@ingredients.route('/ingredient/new', methods=['GET', 'POST'])
@login_required
def new_ingredient():
    recipe_id = request.args.get('recipe_id', default=None, type=int)
    form = IngredientForm()
    if form.validate_on_submit():
        ingredient = Ingredient(name=form.name.data, quantity=form.quantity.data,
                                purchased_at=form.purchased_at.data, recipe_id=recipe_id)
        db.session.add(ingredient)
        db.session.commit()
        flash('Your ingredient has been added!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_ingredient.html', title='New ingredient', form=form, legend='New ingredient')


@ingredients.route('/ingredient/<int:ingredient_id>/update', methods=['GET', 'POST'])
@login_required
def update_ingredient(ingredient_id):
    ingredient = Ingredient.query.get_or_404(ingredient_id)
    recipe = Recipe.query.get(ingredient.recipe_id)
    form = IngredientForm()
    if form.validate_on_submit():
        ingredient.name = form.name.data
        ingredient.quantity = form.quantity.data
        ingredient.purchased_at = form.purchased_at.data
        db.session.commit()
        flash('Your ingredient has been updated!','success')
        return redirect(url_for('recipes.recipe', recipe_id=recipe.id))
    elif request.method == 'GET':
        form.name.data = ingredient.name
        form.quantity.data = ingredient.quantity
        form.purchased_at.data = ingredient.purchased_at
    return render_template('create_ingredient.html', title='Update Ingredient', legend='Update Ingredient',
                           ingredient=ingredient, form=form)

mymeal/main/routes.py
from flask import render_template, request, Blueprint
from mymeal.models import Recipe


main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    recipes = Recipe.query.order_by(Recipe.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', title='Home', recipes=recipes)


@main.route('/about')
def about():
    return render_template('about.html', title='About')

mymeal/recipes/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from mymeal.models import Recipe, Ingredient
from mymeal.recipes.forms import RecipeForm
from flask_login import current_user, login_required
from mymeal import db

recipes = Blueprint('recipes', __name__)


@recipes.route('/recipe/new', methods=['GET', 'POST'])
@login_required
def new_recipe():
    form = RecipeForm()
    if form.validate_on_submit():
        recipe = Recipe(title=form.title.data, serves=form.serves.data, description=form.description.data,
                        recipe_type = form.recipe_type.data,author=current_user,
                        recipe_book=form.recipe_book.data, recipe_book_page=form.recipe_book_page.data)
        db.session.add(recipe)
        db.session.commit()
        flash('Your recipe has been added!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_recipe.html', title='New Recipe', form=form, legend='New Recipe')


@recipes.route('/recipe/<int:recipe_id>')
@login_required
def recipe(recipe_id):
    recipe = Recipe.query.get_or_404(recipe_id)
    ingredients = Ingredient.query.filter_by(recipe_id=recipe_id)
    ingredient_count = Ingredient.query.filter_by(recipe_id=recipe_id).count()
    if ingredient_count == 0:
        ingredient_button_text = 'Add the first ingredient'
    else:
        ingredient_button_text = 'Add another ingredient'

    return render_template('recipe.html', title=recipe.title, recipe=recipe, ingredients=ingredients,
                           count=ingredient_count, ingredient_button_text=ingredient_button_text)


@recipes.route('/recipe/<int:recipe_id>/update', methods=['GET', 'POST'])
@login_required
def update_recipe(recipe_id):
    recipe = Recipe.query.get_or_404(recipe_id)
    if recipe.author != current_user:
        abort(403)
    form = RecipeForm()
    if form.validate_on_submit():
        recipe.title = form.title.data
        recipe.serves = form.serves.data
        recipe.description = form.description.data
        recipe.recipe_type = form.recipe_type.data
        recipe.recipe_book = form.recipe_book.data
        recipe.recipe_book_page = form.recipe_book_page.data
        db.session.commit()
        flash('Your recipe has been updated!','success')
        return redirect(url_for('recipes.recipe', recipe_id=recipe.id))
    elif request.method == 'GET':
        form.title.data = recipe.title
        form.serves.data = recipe.serves
        form.description.data = recipe.description
        form.recipe_type.data = recipe.recipe_type
        form.recipe_book.data = recipe.recipe_book
        form.recipe_book_page.data = recipe.recipe_book_page
    return render_template('create_recipe.html', title='Update Recipe', legend='Update Recipe', recipe=recipe, form=form)


@recipes.route('/recipe/<int:recipe_id>/delete', methods=['POST'])
@login_required
def delete_recipe(recipe_id):
    recipe = Recipe.query.get_or_404(recipe_id)
    if recipe.author != current_user:
        abort(403)

    db.session.delete(recipe)
    db.session.commit()
    flash('Your recipe has been deleted!', 'success')
    return redirect(url_for('main.home'))

mymeal/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from mymeal import db, bcrypt
from mymeal.models import User, Recipe
from mymeal.users.forms import LoginForm, RegistrationForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from mymeal.users.utils import save_picture, send_reset_email
from flask_login import login_user, current_user, logout_user, login_required


users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created, you can now login!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login unsuccessful, check username and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route('/user/<string:username>')
def user_recipes(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    recipes = Recipe.query.filter_by(author=user).order_by(Recipe.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_recipe.html', recipes=recipes, user=user)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been changed, you can now login!', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

mymeal/weekly/routes.py
from flask import render_template, Blueprint, request, redirect, url_for
from flask_login import login_required, current_user
from mymeal.weekly.forms import ThisWeekForm, ThisWeeksIngredients
from mymeal.models import Mealplan, Ingredient
from mymeal import db


weekly = Blueprint('weekly', __name__)


@weekly.route('/week/new', methods=['GET', 'POST'])
@login_required
def new_week():
    form = ThisWeekForm()
    if request.method == 'POST':
        week = current_user.meal_plan_count + 1
        week_description = 'week ' + str(week)
        dirty_table = False

        if int(form.saturdaySelect.data) != 0:
            dirty_table=True
            saturdaymeal = Mealplan(week=week, day_of_meal='saturday', meal_id=form.saturdaySelect.data,
                                    week_description=week_description, creator=current_user)
            db.session.add(saturdaymeal)

        if int(form.sundaySelect.data) != 0:
            dirty_table = True
            sundaymeal = Mealplan(week=week, day_of_meal='sunday', meal_id=form.sundaySelect.data, week_description=week_description, creator=current_user)
            db.session.add(sundaymeal)

        if int(form.mondaySelect.data) != 0:
            dirty_table = True
            mondaymeal = Mealplan(week=week, day_of_meal='monday', meal_id=form.mondaySelect.data, week_description=week_description, creator=current_user)
            db.session.add(mondaymeal)

        if int(form.tuesdaySelect.data) != 0:
            dirty_table = True
            tuesdaymeal = Mealplan(week=week, day_of_meal='tuesday', meal_id=form.tuesdaySelect.data, week_description=week_description, creator=current_user)
            db.session.add(tuesdaymeal)

        if int(form.wednesdaySelect.data) != 0:
            dirty_table = True
            wednesdaymeal = Mealplan(week=week, day_of_meal='wednesday', meal_id=form.wednesdaySelect.data, week_description=week_description, creator=current_user)
            db.session.add(wednesdaymeal)

        if int(form.thursdaySelect.data) != 0:
            dirty_table = True
            thursdaymeal = Mealplan(week=week, day_of_meal='thursday', meal_id=form.thursdaySelect.data, week_description=week_description, creator=current_user)
            db.session.add(thursdaymeal)

        if int(form.fridaySelect.data) != 0:
            dirty_table = True
            fridaymeal = Mealplan(week=week, day_of_meal='friday', meal_id=form.fridaySelect.data, week_description=week_description, creator=current_user)
            db.session.add(fridaymeal)

        if dirty_table:
            setattr(current_user, 'meal_plan_count', week)
            db.session.commit()
            return redirect(url_for('weekly.week_ingredients'))
    return render_template('thisweek.html', title='This Week', form=form)


@weekly.route('/week/ingredients', methods=['GET', 'POST'])
@login_required
def week_ingredients():
    form = ThisWeeksIngredients()

    if form.validate_on_submit():
        return redirect(url_for('main.home'))
    else:

        meals_this_week = Mealplan.query.filter_by(user_id=current_user.id, week=current_user.meal_plan_count).all()
        supermarket = []
        greengrocers = []
        butchers = []

        for meals in meals_this_week:
            ingredients = Ingredient.query.filter_by(recipe_id=meals.meal_id)
            for ii in ingredients:
                if ii.purchased_at == 'supermarket':
                    supermarket.append(ii.quantity + ' ' + ii.name)
                if ii.purchased_at == 'greengrocer':
                    greengrocers.append(ii.quantity + ' ' + ii.name)
                if ii.purchased_at == 'butchers':
                    butchers.append(ii.quantity + ' ' + ii.name)

    return render_template('weekly_ingredients.html', title='Ingredients', form=form, supermarket=supermarket, butchers=butchers, greengrocers=greengrocers)

mymeal/templates/about.html
{% extends 'layout.html' %}
{% block content %}
    <h1>About</h1>
{% endblock content %}

mymeal/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
            <form method="POST" action="", enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Account</legend>
                    <div class="form-group">
                        {{ form.username.label(class="form-control-label") }}

                        {% if form.username.errors %}
                            {{ form.username(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.username(class="form-control form-control-lg") }}
                        {% endif %}

                    </div>
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.picture.label() }}
                        {{ form.picture(class="form-control-file") }}
                        {% if form.picture.errors %}
                            {% for error in form.picture.errors %}
                                <span class="text-danger">{{ error }}</span></br>
                            {% endfor %}
                        {% endif %}

                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </form>
    </div>
{% endblock content %}

mymeal/templates/home.html
{% extends 'layout.html' %}
{% block content %}
    {% for recipe in recipes.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + recipe.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_recipes', username=recipe.author.username) }}">{{ recipe.author.username }}</a>
              <small class="text-muted">{{ recipe.date_posted.strftime('%d-%m-%Y') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('recipes.recipe', recipe_id=recipe.id) }}">{{ recipe.title }}</a></h2>
            <p class="article-content">{{ recipe.description }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in recipes.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if recipes.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock %}

mymeal/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
    <title>Meal Planner - {{ title }}</title>
    {% else %}
     <title>Meal Planner</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Meal Planner</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{ url_for('recipes.new_recipe') }}">Create Recipe</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                    <img class="rounded-circle  article-img" src="{{ url_for('static', filename='profile_pics/' + current_user.image_file) }}">
                {% else %}
                  <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
            <div class="content-section">
            <h3>Your Options</h3>
                <table class="table table-hover">
                  <thead>
                  </thead>
                  <tbody>
                    <tr>
                      <td>
                          <a class="nav-item nav-link" href="{{ url_for('weekly.new_week') }}">Weekly Planner</a>
                      </td>
                    </tr>
                    <tr>
                      <td>
                          <a class="nav-item nav-link disabled" href="#">Latest Meals</a>
                      </td>
                    </tr>
                    <tr>
                      <td>
                          <a class="nav-item nav-link disabled" href="#">Announcements</a>
                      </td>
                    </tr>
                    <tr>
                      <td>
                          <a class="nav-item nav-link disabled" href="#">Calendar</a>
                      </td>
                    </tr>
                  </tbody>
                </table>
          </div>
        </div>
      </div>
    </main>

<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

mymeal/templates/login.html
{% extends 'layout.html' %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">]
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}

                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">]
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>

        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need an account?<a class="ml-2" href="{{ url_for('users.register') }}">Sign up now</a>
        </small>
    </div>
{% endblock content %}

mymeal/templates/recipe.html
{% extends "layout.html" %}
{% block content %}

    <article class="media content-section">
        <img class="rounded-circle article-img"src="{{ url_for('static', filename='profile_pics/' + recipe.author.image_file) }}">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{{ url_for('users.user_recipes', username=recipe.author.username) }}">{{ recipe.author.username }}</a>
          <small class="text-muted">{{ recipe.date_posted.strftime('%d-%m-%Y') }}</small>
            {% if recipe.author == current_user %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('recipes.update_recipe', recipe_id=recipe.id) }}">Update</a>
                <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
            </div>
            {% endif %}
        </div>
        <div class="container">
              <div class="row">
                  <h2>{{ recipe.title }}
                      <small class="text-muted">
                        {{ recipe.recipe_book }} book on page {{ recipe.recipe_book_page }}
                      </small>
                  </h2>
              </div>
        </div>

        <p class="article-content">{{ recipe.description }}</p>
        <hr/>
          {% if count > 0 %}
            <h3 class="article-title">Ingredients List</h3>
              {% for ingredient in ingredients %}
                        <ul class="list-group">
                            <li class="list-group-item border-0">
                                <a class="btn btn-outline-secondary btn-sm" href="{{ url_for('ingredients.update_ingredient', ingredient_id=ingredient.id) }}">Modify</a>
                                {{ ingredient.quantity }} {{ ingredient.name }} purchased from the {{ ingredient.purchased_at }}
                            </li>
                        </ul>
              {% endfor %}
          {% else %}
          <p>No ingredients added</p>
          {% endif %}
          <a class="btn btn-primary btn-sm mt-1 mb-1" href="{{ url_for('ingredients.new_ingredient', recipe_id=recipe.id) }}">{{ ingredient_button_text }}</a>
      </div>
    </article>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete Recipe?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{ url_for('recipes.delete_recipe', recipe_id=recipe.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

mymeal/templates/user_recipe.html
{% extends 'layout.html' %}
{% block content %}
    <h2 class="mb-3">Recipes by {{ user.username }} ({{ recipes.total }})</h2>
    {% for recipe in recipes.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + recipe.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_recipes', username=recipe.author.username) }}">{{ recipe.author.username }}</a>
              <small class="text-muted">{{ recipe.date_posted.strftime('%d-%m-%Y') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('recipes.recipe', recipe_id=recipe.id) }}">{{ recipe.title }} {{ recipe.id }}</a></h2>
            <p class="article-content">{{ recipe.description }}</p>
          <hr/>
          </div>
        </article>
    {% endfor %}
    {% for page_num in recipes.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if recipes.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('users.user_recipes', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_recipes', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock %}